Feature/mdp2
ETICINSATechnologies/AnnuaireAncien_v2.0 pull request #14
Opened 2019-03-11 19:50 UTC by sadsithalokuge

2019-03-12 10:05 UTC, laurenttainturier requested changes
Après discussion avec Alex,, ce serait bien que la modif du password ne persiste en base que le mdp, mais que les infos du profile ayant été modifiées (sans être persistées) restent affichées.

2019-03-12 10:05 UTC, laurenttainturier commented on src/Components/PositionForm/PositionForm.tsx
> +        if (typeof(this.props.memberPositions)!== 'undefined' &&this.props.memberPositions.length !== 0) {
Tu as vraiment besoin de vérifier qu'il n'est pas udefined ?
Dans typescript on dit que `props.memberPositions` est un `memberPosition[]`

2019-03-12 10:05 UTC, laurenttainturier commented on src/Components/Modal/Modal.tsx
> +                    <div className="content">
Tu peux faire :
```js
return ({
    !props.show ? '' :
    <div className="Modal">
    ...
})
```

2019-03-13 20:41 UTC, sadsithalokuge commented on src/Components/Modal/Modal.tsx
> +                    <div className="content">
Bien vu

2019-03-13 20:43 UTC, sadsithalokuge commented on src/Components/PositionForm/PositionForm.tsx
> +        if (typeof(this.props.memberPositions)!== 'undefined' &&this.props.memberPositions.length !== 0) {
Oui effectivement, dans ce cas .length sera toujours bien défini

2019-03-18 21:05 UTC, merged