Feature/affichageprofil
ETICINSATechnologies/AnnuaireAncien_v2.0 pull request #6
Opened 2019-02-07 22:18 UTC by sadsithalokuge

Display and modify member details

2019-02-08 09:07 UTC, laurenttainturier requested changes
C'est vraiment bien ! Je t'ai laissé quelques remarques avant de merge

2019-02-08 09:07 UTC, laurenttainturier commented on npm-debug.log
> +0 info it worked if it ends with ok
Ce fichier ne doit pas être commit

2019-02-08 09:07 UTC, laurenttainturier commented on src/Components/PositionForm/PositionForm.css
> +.position_container {
Une bonne pratique est d'indiquer la classe du composant afin de garantir l'absence de conflit avec d'autres composants.

2019-02-08 09:07 UTC, laurenttainturier commented on src/Components/PositionForm/PositionForm.js
> +            positionids: [],
`positionIds` c'est mieux

2019-02-08 09:07 UTC, laurenttainturier commented on src/Components/PositionForm/PositionForm.js
> +    onChange(event) {
Ne sert plus à rien, non ?

2019-02-08 09:07 UTC, laurenttainturier commented on src/Components/PositionForm/PositionForm.js
> +    updatePositionid (position) {
updatePositionId

2019-02-08 09:07 UTC, laurenttainturier commented on src/Components/PositionForm/PositionForm.js
> +                        key={index} year={null} positions={this.state.positions} positionid={positionid} updatePositionid={updatePositionid} index={index} modifyEnabled={this.state.modifyEnabled} del
Cette ligne me semble un peu longue

2019-02-08 09:07 UTC, laurenttainturier commented on src/Components/PositionForm/PositionForm.js
> +                <Button className={`input_button add_position ${this.state.modifyEnabled ? 'visible' : 'hidden'}`} value="Ajouter" onClick={() => this.addPosition()}/>
Elle aussi

2019-02-08 09:07 UTC, laurenttainturier commented on src/Components/PositionForm/PositionForm.js
> +                    <select disabled={!this.state.modifyEnabled} className="position dropdown" value={this.state.positionid} onChange={this.onChange}>
Celles-ci aussi

2019-02-08 09:07 UTC, laurenttainturier commented on src/Components/ProfileForm/ProfileForm.js
> +            <select className="department" value={this.state.info.department === null ? 0:this.state.info.department.id} onChange={this.onChange} disabled={!this.state.modifyEnabled} >
Là aussi essaye de splitter les lignes

2019-02-12 18:56 UTC, sadsithalokuge commented on src/Components/PositionForm/PositionForm.css
> +.position_container {
c'est fait ! merci

2019-02-12 18:56 UTC, sadsithalokuge commented on src/Components/PositionForm/PositionForm.js
> +            positionids: [],
Done

2019-02-12 18:56 UTC, sadsithalokuge commented on src/Components/PositionForm/PositionForm.js
> +    onChange(event) {
Effectivement

2019-02-12 18:56 UTC, sadsithalokuge commented on src/Components/PositionForm/PositionForm.js
> +    updatePositionid (position) {
Done

2019-02-12 18:57 UTC, sadsithalokuge commented on src/Components/PositionForm/PositionForm.js
> +                        key={index} year={null} positions={this.state.positions} positionid={positionid} updatePositionid={updatePositionid} index={index} modifyEnabled={this.state.modifyEnabled} del
Yep, done

2019-02-22 21:53 UTC, laurenttainturier approved these changes

2019-02-23 14:44 UTC, merged